import { IDownloadTestResults } from '../types/types';


const forumPost = (country: string, isp: string, avgSpeed: number, tests: IDownloadTestResults): string => {
    const summary: string = `[b]Country:[/b] ${country}\n[b]Internet Service Provider (ISP):[/b] ${isp}\n[b]CDN Test:[/b] ${tests.cdnTest.speed}MB/s\n[b]Average Download Speed (non-Nexus downloads):[/b] ${avgSpeed}MB/s\n\n`;
    const dlResults = Object.entries(tests.serverTests).map(([key, res]) => `[*]${key}: ${res.speed.toFixed(1)}MB/s (${res.rating})[/*]`).join('\n');
    const downloadTests: string = `[b]Download Tests:[/b]\n[LIST]\n${dlResults}\n[/LIST]\n\n`;
    const dlLinks = `[b]Download links:[/b]\n[LIST]\n[*]Large File Download: ${tests.largeFileExample || 'Failed'}[/*]\n[*]Small File Download: ${tests.smallFileExample || 'Failed'}[/*]\n[/LIST]\n\n`;
    const trace = `[/b]TraceRoute Results:[/b]\n[code]${tests.trace}[/code]`;

    return `${summary}${downloadTests}${dlLinks}${trace}\n\nDownload tests generated by Vortex`;
}

export default forumPost;